/**
 * Seed products for the inventory system
 * References will be resolved during seeding by looking up category/supplier by name
 *
 * Note: categoryRef and supplierRef are name strings that will be resolved to ObjectIds during seeding
 */
export const seedProducts = [
  // Electronics
  {
    title: 'Wireless Mouse',
    sku: 'ELEC-WM-001',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 12.50,
    salePrice: 24.99,
    quantity: 150,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'USB-C Cable 2m',
    sku: 'ELEC-USBC-002',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 5.00,
    salePrice: 12.99,
    quantity: 300,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Laptop Stand',
    sku: 'ELEC-LS-003',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 25.00,
    salePrice: 49.99,
    quantity: 45,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Webcam HD 1080p',
    sku: 'ELEC-WC-004',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 35.00,
    salePrice: 69.99,
    quantity: 8,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Keyboard Mechanical RGB',
    sku: 'ELEC-KB-005',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 45.00,
    salePrice: 89.99,
    quantity: 0,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Office Supplies
  {
    title: 'A4 Paper Ream',
    sku: 'OFF-A4-001',
    categoryRef: 'Office Supplies',
    supplierRef: 'Office Depot Wholesale',
    costPrice: 3.50,
    salePrice: 7.99,
    quantity: 500,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Ballpoint Pens Box',
    sku: 'OFF-PEN-002',
    categoryRef: 'Office Supplies',
    supplierRef: 'Office Depot Wholesale',
    costPrice: 8.00,
    salePrice: 15.99,
    quantity: 120,
    unitOfMeasure: 'box',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Stapler Heavy Duty',
    sku: 'OFF-STA-003',
    categoryRef: 'Office Supplies',
    supplierRef: 'Office Depot Wholesale',
    costPrice: 12.00,
    salePrice: 22.99,
    quantity: 35,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Filing Folders Pack',
    sku: 'OFF-FF-004',
    categoryRef: 'Office Supplies',
    supplierRef: 'Office Depot Wholesale',
    costPrice: 6.00,
    salePrice: 12.99,
    quantity: 200,
    unitOfMeasure: 'box',
    imageUrl: null,
    status: 'active',
  },

  // Furniture
  {
    title: 'Office Desk Adjustable',
    sku: 'FURN-DESK-001',
    categoryRef: 'Furniture',
    supplierRef: 'Industrial Furniture Inc.',
    costPrice: 250.00,
    salePrice: 499.99,
    quantity: 12,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Ergonomic Office Chair',
    sku: 'FURN-CHAIR-002',
    categoryRef: 'Furniture',
    supplierRef: 'Industrial Furniture Inc.',
    costPrice: 180.00,
    salePrice: 349.99,
    quantity: 18,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Storage Cabinet 4-Drawer',
    sku: 'FURN-CAB-003',
    categoryRef: 'Furniture',
    supplierRef: 'Industrial Furniture Inc.',
    costPrice: 120.00,
    salePrice: 249.99,
    quantity: 6,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Tools & Equipment
  {
    title: 'Cordless Drill Kit',
    sku: 'TOOL-DR-001',
    categoryRef: 'Tools & Equipment',
    supplierRef: 'Global Tools Distribution',
    costPrice: 75.00,
    salePrice: 149.99,
    quantity: 25,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Socket Wrench Set',
    sku: 'TOOL-WR-002',
    categoryRef: 'Tools & Equipment',
    supplierRef: 'Global Tools Distribution',
    costPrice: 45.00,
    salePrice: 89.99,
    quantity: 30,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Measuring Tape 10m',
    sku: 'TOOL-MT-003',
    categoryRef: 'Tools & Equipment',
    supplierRef: 'Global Tools Distribution',
    costPrice: 8.00,
    salePrice: 16.99,
    quantity: 80,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Utility Knife Set',
    sku: 'TOOL-UK-004',
    categoryRef: 'Tools & Equipment',
    supplierRef: 'Global Tools Distribution',
    costPrice: 15.00,
    salePrice: 29.99,
    quantity: 5,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Packaging Materials
  {
    title: 'Cardboard Boxes Large',
    sku: 'PACK-BOX-001',
    categoryRef: 'Packaging Materials',
    supplierRef: 'PackRight Solutions',
    costPrice: 1.50,
    salePrice: 3.99,
    quantity: 1000,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Bubble Wrap Roll',
    sku: 'PACK-BW-002',
    categoryRef: 'Packaging Materials',
    supplierRef: 'PackRight Solutions',
    costPrice: 12.00,
    salePrice: 24.99,
    quantity: 50,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Packing Tape 6-Pack',
    sku: 'PACK-TAPE-003',
    categoryRef: 'Packaging Materials',
    supplierRef: 'PackRight Solutions',
    costPrice: 8.00,
    salePrice: 16.99,
    quantity: 150,
    unitOfMeasure: 'box',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Stretch Film Roll',
    sku: 'PACK-SF-004',
    categoryRef: 'Packaging Materials',
    supplierRef: 'PackRight Solutions',
    costPrice: 18.00,
    salePrice: 35.99,
    quantity: 40,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Cleaning Supplies
  {
    title: 'Multi-Surface Cleaner 5L',
    sku: 'CLEAN-MSC-001',
    categoryRef: 'Cleaning Supplies',
    supplierRef: 'CleanPro Supplies',
    costPrice: 15.00,
    salePrice: 29.99,
    quantity: 60,
    unitOfMeasure: 'l',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Microfiber Cloths Pack',
    sku: 'CLEAN-MFC-002',
    categoryRef: 'Cleaning Supplies',
    supplierRef: 'CleanPro Supplies',
    costPrice: 10.00,
    salePrice: 19.99,
    quantity: 90,
    unitOfMeasure: 'box',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Industrial Mop Set',
    sku: 'CLEAN-MOP-003',
    categoryRef: 'Cleaning Supplies',
    supplierRef: 'CleanPro Supplies',
    costPrice: 25.00,
    salePrice: 49.99,
    quantity: 15,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Safety Equipment
  {
    title: 'Safety Glasses Box',
    sku: 'SAFE-SG-001',
    categoryRef: 'Safety Equipment',
    supplierRef: 'SafetyFirst Equipment',
    costPrice: 20.00,
    salePrice: 39.99,
    quantity: 50,
    unitOfMeasure: 'box',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Work Gloves Heavy Duty',
    sku: 'SAFE-GLV-002',
    categoryRef: 'Safety Equipment',
    supplierRef: 'SafetyFirst Equipment',
    costPrice: 8.00,
    salePrice: 16.99,
    quantity: 200,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Hard Hat Yellow',
    sku: 'SAFE-HH-003',
    categoryRef: 'Safety Equipment',
    supplierRef: 'SafetyFirst Equipment',
    costPrice: 12.00,
    salePrice: 24.99,
    quantity: 35,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'First Aid Kit Large',
    sku: 'SAFE-FAK-004',
    categoryRef: 'Safety Equipment',
    supplierRef: 'SafetyFirst Equipment',
    costPrice: 40.00,
    salePrice: 79.99,
    quantity: 3,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Raw Materials
  {
    title: 'Steel Rods 2m',
    sku: 'RAW-SR-001',
    categoryRef: 'Raw Materials',
    supplierRef: 'RawMaterials Direct',
    costPrice: 25.00,
    salePrice: 49.99,
    quantity: 100,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Plastic Sheets 4mm',
    sku: 'RAW-PS-002',
    categoryRef: 'Raw Materials',
    supplierRef: 'RawMaterials Direct',
    costPrice: 15.00,
    salePrice: 29.99,
    quantity: 75,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },
  {
    title: 'Aluminum Bars 1m',
    sku: 'RAW-AB-003',
    categoryRef: 'Raw Materials',
    supplierRef: 'RawMaterials Direct',
    costPrice: 18.00,
    salePrice: 35.99,
    quantity: 120,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Products without supplier (demonstrating optional supplier)
  {
    title: 'Generic Label Maker',
    sku: 'OFF-LM-099',
    categoryRef: 'Office Supplies',
    supplierRef: null,
    costPrice: 30.00,
    salePrice: 59.99,
    quantity: 10,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'active',
  },

  // Archived product example
  {
    title: 'Old Model Scanner',
    sku: 'ELEC-SCAN-OLD',
    categoryRef: 'Electronics',
    supplierRef: 'TechSupply Co.',
    costPrice: 80.00,
    salePrice: 150.00,
    quantity: 2,
    unitOfMeasure: 'pcs',
    imageUrl: null,
    status: 'archived',
  },
];
